### ISSUE TITLE
cfn generate failed with ca-cert not found

### ISSUE THREAD

**Issue by wyuzheng** [aws-cloudformation/cloudformation-cli#381]
Hi there, 

I am having an issue when calling `cfn generate` when generating files after `init` and create resource schema json file. It failed with error `OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-bundle.crt`. 

Stacktrace is:
```
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
```

Anyone have idea about this?

Attachment with full error log in rpdk.log
```
[2020-01-17T00:31:05Z] DEBUG    - Logging set up successfully
[2020-01-17T00:31:05Z] DEBUG    - Running generate: Namespace(command=<function generate at 0x102f05840>, subparser_name='generate', verbose=0, version=False)
[2020-01-17T00:31:05Z] DEBUG    - Root directory: /Users/wyuzheng/ImageBuilder/AWSCloudFormationResourceProvidersImageBuilder/src/AWSCloudFormationResourceProvidersImageBuilder/component
[2020-01-17T00:31:05Z] DEBUG    - Loading project file '/Users/wyuzheng/ImageBuilder/AWSCloudFormationResourceProvidersImageBuilder/src/AWSCloudFormationResourceProvidersImageBuilder/component/.rpdk-config'
[2020-01-17T00:31:05Z] INFO     - Validating your resource specification...
[2020-01-17T00:31:05Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jsonschema/validators.py", line 774, in resolve_from_url
    document = self.store[url]
  File "/usr/local/lib/python3.6/site-packages/jsonschema/_utils.py", line 22, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: 'https://json-schema.org/draft-07/schema'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jsonschema/validators.py", line 777, in resolve_from_url
    document = self.resolve_remote(url)
  File "/usr/local/lib/python3.6/site-packages/jsonschema/validators.py", line 856, in resolve_remote
    result = self.handlers[scheme](uri)
  File "/usr/local/lib/python3.6/site-packages/rpdk/core/data_loaders.py", line 60, in get_with_timeout
    return requests.get(uri, timeout=timeout).json()
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 228, in cert_verify
    "invalid path: {}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-bundle.crt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/usr/local/lib/python3.6/site-packages/rpdk/core/generate.py", line 14, in generate
    project.load()
  File "/usr/local/lib/python3.6/site-packages/rpdk/core/project.py", line 255, in load
    self.load_schema()
  File "/usr/local/lib/python3.6/site-packages/rpdk/core/project.py", line 191, in load_schema
    self.schema = load_resource_spec(f)
  File "/usr/local/lib/python3.6/site-packages/rpdk/core/data_loaders.py", line 102, in load_resource_spec
    validator.validate(resource_spec)
  File "/usr/local/lib/python3.6/site-packages/jsonschema/validators.py", line 352, in validate
    for error in self.iter_errors(*args, **kwargs):
  File "/usr/local/lib/python3.6/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.6/site-packages/jsonschema/_validators.py", line 286, in properties
    schema_path=property,
  File "/usr/local/lib/python3.6/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python3.6/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.6/site-packages/jsonschema/_validators.py", line 259, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/usr/local/lib/python3.6/site-packages/jsonschema/validators.py", line 766, in resolve
    return url, self._remote_cache(url)
  File "/usr/local/lib/python3.6/site-packages/jsonschema/validators.py", line 779, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-bundle.crt
```

**Comment by tobywf** [comment]
Sorry we haven't responded to this. I think this is an issue with your machine you need to look into more. Did you install the CloudFormation CLI via `pip`/PyPI in a virtualenv?

**Comment by PatMyron** [comment]
couple links to troubleshoot the `TLS CA certificate bundle` error:
https://stackoverflow.com/questions/49100986/certbot-could-not-find-a-suitable-tls-ca-certificate-bundle-archlinux
https://unix.stackexchange.com/questions/339613/arch-linux-ca-certificates-crt-not-found
