### ISSUE TITLE
cfn init unhandled exception

### ISSUE THREAD

**Issue by PatMyron** [aws-cloudformation/cloudformation-cli#415]
```shell
$ cfn init
Initializing new project
What's the name of your resource type?
(Organization::Service::Resource)
>> AWS::GameLift::Build
One language plugin found, defaulting to java
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
Please include the log file 'rpdk.log'
```

```
[2020-04-09T00:08:02Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/Users/$USER/Library/Python/3.7/lib/python/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/Users/$USER/Library/Python/3.7/lib/python/site-packages/rpdk/core/init.py", line 158, in wrapper
    function(args)
  File "/Users/$USER/Library/Python/3.7/lib/python/site-packages/rpdk/core/init.py", line 148, in init
    project.init(type_name, language)
  File "/Users/$USER/Library/Python/3.7/lib/python/site-packages/rpdk/core/project.py", line 187, in init
    self._plugin = load_plugin(language)
  File "/Users/$USER/Library/Python/3.7/lib/python/site-packages/rpdk/core/plugin_registry.py", line 12, in load_plugin
    return PLUGIN_REGISTRY[language]()()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2445, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (attrs 19.1.0 (/usr/local/lib/python3.7/site-packages), Requirement.parse('attrs>=19.2.0'), {'hypothesis'})
```

**Comment by PatMyron** [comment]
solved with virtual environment:
```shell
python3 -m venv env
source env/bin/activate
pip3 install cloudformation-cli cloudformation-cli-java-plugin
```
