### ISSUE TITLE
Doc generator fails on objects with patternProperties

### ISSUE THREAD

**Issue by arnulfojr** [aws-cloudformation/cloudformation-cli#418]
Hi!

According to the resource schema, specifying both properties and patternProperties is not allowed and validation fails... https://github.com/aws-cloudformation/aws-cloudformation-resource-schema#constraints

But when having an schema with patternProperties the doc generation fails.
I have this property that is referenced as a definition and the definition looks like:

```
// ignore the regex :)
    "SomeProp": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        ".*": {
          "type": "string",
          "maxLength": 30000
        }
      }
    },
```

I peek in the code and it seems that the doc generation assumes that all objects have properties and no "patternProperties" exists.

https://github.com/aws-cloudformation/cloudformation-cli/blob/c2f4ff2128a52fa51c9d9bf6cc8c4922da17f831/src/rpdk/core/project.py#L431-L439

The stack trace is:
```
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File ".../lib/python3.6/site-packages/rpdk/core/generate.py", line 16, in generate
    project.generate_docs()
  File ".../lib/python3.6/site-packages/rpdk/core/project.py", line 353, in generate_docs
    for name, value in docs_schema["properties"].items()
  File ".../lib/python3.6/site-packages/rpdk/core/project.py", line 353, in <dictcomp>
    for name, value in docs_schema["properties"].items()
  File ".../lib/python3.6/site-packages/rpdk/core/project.py", line 426, in _set_docs_properties
    propname, prop["items"], proppath
  File ".../lib/python3.6/site-packages/rpdk/core/project.py", line 437, in _set_docs_properties
    for name, value in prop["properties"].items()
  File ".../lib/python3.6/site-packages/rpdk/core/project.py", line 437, in <dictcomp>
    for name, value in prop["properties"].items()
  File ".../lib/python3.6/site-packages/rpdk/core/project.py", line 437, in _set_docs_properties
    for name, value in prop["properties"].items()
KeyError: 'properties'
```

**Comment by ammokhov** [comment]
looks like this issue is no longer there, should we close it?
