### ISSUE TITLE
template.yaml ambiguity

### ISSUE THREAD

**Issue by richardhboyd** [aws-cloudformation/cloudformation-cli#428]
The CLI seems to become confused if there is both a `template.yaml` and `template.yml` file in the root of the project.

````bash
[2020-04-27T20:33:03Z] DEBUG    - Sending request
{
  "credentials": {
    "accessKeyId": "<redacted by me>",
    "secretAccessKey": "<redacted by me>",
    "sessionToken": "<redacted by me>"
  },
  "action": "CREATE",
  "request": {
    "clientRequestToken": "ecba020e-b2e6-4742-a7d0-8a06ae7c4b2b",
    "desiredResourceState": {
      "Title": "foo-rhboyd-adsfhaldiasdglffffhiu"
    },
    "previousResourceState": null,
    "logicalResourceIdentifier": null
  },
  "callbackContext": null
}
[2020-04-27T20:33:03Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/rpdk/core/invoke.py", line 42, in invoke
    response = client._call(payload)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/rpdk/core/contract/resource_client.py", line 249, in _call
    FunctionName=self._function_name, Payload=payload.encode("utf-8")
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ResourceNotFound) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:012345678901:function:TestEntrypoint
````

to reproduce:
````bash
mkdir my-bug
cd my-bug/
cfn init
# remove TestCode from required
cfn generate
cfn submit --dry-run
touch template.yaml
sam local start-lambda
````

Second terminal:
````bash
cfn invoke CREATE test.json
````

**Comment by mircealam** [comment]
This is sam and the order in which the template file is being searched.
Sam first looks for template.yaml and after that for template.yml

without template.yaml:
```shell 
sam local start-lambda --debug
2023-10-06 16:28:21,593 | No config file found in this directory.
2023-10-06 16:28:21,596 | OSError occurred while reading TOML file: [Errno 2] No such file or directory: '/private/tmp/1/my-bug/samconfig.toml'
2023-10-06 16:28:21,597 | Config file location: /private/tmp/1/my-bug/samconfig.toml
2023-10-06 16:28:21,598 | Config file '/private/tmp/1/my-bug/samconfig.toml' does not exist
2023-10-06 16:28:21,601 | Using SAM Template at /private/tmp/1/my-bug/template.yml
2023-10-06 16:28:21,627 | Using config file: samconfig.toml, config environment: default
2023-10-06 16:28:21,628 | Expand command line arguments to:
2023-10-06 16:28:21,629 | --template_file=/private/tmp/1/my-bug/template.yml --host=127.0.0.1 --port=3001 --layer_cache_basedir=/Users/liv/.aws-sam/layers-pkg
--container_host=localhost --container_host_interface=127.0.0.1
```

with template.yaml:
```shell 
sam local start-lambda --debug
2023-10-06 16:30:19,458 | No config file found in this directory.
2023-10-06 16:30:19,462 | OSError occurred while reading TOML file: [Errno 2] No such file or directory: '/private/tmp/1/my-bug/samconfig.toml'
2023-10-06 16:30:19,463 | Config file location: /private/tmp/1/my-bug/samconfig.toml
2023-10-06 16:30:19,464 | Config file '/private/tmp/1/my-bug/samconfig.toml' does not exist
2023-10-06 16:30:19,465 | Using SAM Template at /private/tmp/1/my-bug/template.yaml
2023-10-06 16:30:19,503 | Using config file: samconfig.toml, config environment: default
2023-10-06 16:30:19,504 | Expand command line arguments to:
2023-10-06 16:30:19,504 | --template_file=/private/tmp/1/my-bug/template.yaml --host=127.0.0.1 --port=3001 --layer_cache_basedir=/Users/liv/.aws-sam/layers-pkg
--container_host=localhost --container_host_interface=127.0.0.1
```

For reference: 
https://github.com/aws/aws-sam-cli/blob/8126aaac29ff8706b14f29a126ab7bb829d81b24/samcli/lib/iac/cfn/cfn_iac.py#L179 
and 
https://github.com/aws/aws-sam-cli/blob/8126aaac29ff8706b14f29a126ab7bb829d81b24/samcli/lib/iac/iac_factory.py#L48

While this is confusing this is the expected behavior (template.yaml getting priority over template.yml) and if there was a desired change in behavior, this is something that would need to be addressed in SAM cli tool not in this tool.
