### ISSUE TITLE
Improve error message: "Unhandled exception" when json-schema.org endpoint is unavailable

### ISSUE THREAD

**Issue by vladtsir** [aws-cloudformation/cloudformation-cli#429]
If https://json-schema.org is unavailable, the error is reported back as an "Unhandled exception". 

Please improve error reporting.

```
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
Please include the log file 'rpdk.log'
```

partial stack trace:

```
...
Traceback (most recent call last):
  File "/redactedPath/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/redactedPath/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/redactedPath/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/redactedPath/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/redactedPath/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f751a41bf90>, 'Connection to json-schema.org timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/redactedPath/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/redactedPath/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/redactedPath/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='json-schema.org', port=443): Max retries exceeded with url: /draft-07/schema (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f751a41bf90>, 'Connection to json-schema.org timed out. (connect timeout=10)'))
```

**Comment by vladtsir** [comment]
probably related to https://github.com/aws-cloudformation/cloudformation-cli/issues/422

**Comment by wbingli** [comment]
Duplicate issue #228
