### ISSUE TITLE
`cfn-cli submit` fails on validation of `ExecutionRoleArn`

### ISSUE THREAD

**Issue by bkabrda** [aws-cloudformation/cloudformation-cli#447]
Hey 👋 I'm trying to upload a new version of one of the [Datadog cloudformation resources](https://github.com/DataDog/datadog-cloudformation-resources), more specifically the `datadog-monitors-monitor-handler`. While running `cfn-cli submit -v --region us-west-2`, I'm getting the following traceback in `rpdk.log`:

```
[2020-05-28T08:31:47Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/Users/slavek.kabrda/programming/datadog-cloudformation-resources/venv/lib/python3.7/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/Users/slavek.kabrda/programming/datadog-cloudformation-resources/venv/lib/python3.7/site-packages/rpdk/core/submit.py", line 21, in submit
    args.set_default,
  File "/Users/slavek.kabrda/programming/datadog-cloudformation-resources/venv/lib/python3.7/site-packages/rpdk/core/project.py", line 343, in submit
    f, endpoint_url, region_name, role_arn, use_role, set_default
  File "/Users/slavek.kabrda/programming/datadog-cloudformation-resources/venv/lib/python3.7/site-packages/rpdk/core/project.py", line 515, in _upload
    response = cfn_client.register_type(**kwargs)
  File "/Users/slavek.kabrda/programming/datadog-cloudformation-resources/venv/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/slavek.kabrda/programming/datadog-cloudformation-resources/venv/lib/python3.7/site-packages/botocore/client.py", line 608, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/slavek.kabrda/programming/datadog-cloudformation-resources/venv/lib/python3.7/site-packages/botocore/client.py", line 656, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/slavek.kabrda/programming/datadog-cloudformation-resources/venv/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "ExecutionRoleArn", must be one of: Type, TypeName, SchemaHandlerPackage, LoggingConfig, ClientRequestToken
```

I tried removing all the generated files including `resource-role.yaml` and regenerating using `cfn-cli generate`, but I'm still getting the same error.

`pip list` shows these versions of libraries that are included in the traceback:

```
botocore                       1.16.15
cloudformation-cli             0.1.3
```

Am I doing something wrong or is this an issue?
Thanks!

**Comment by wbingli** [comment]
Could you make sure you have the latest AWS CLI?  Basically  verify `--execution-role-arn` supported if run `aws cloudformation register-type help`.

Also double check if have an override cloudformation CLI model  under `~/.aws/models/cloudformation`. If so, you should remove it, and it will use the default cloudformation model from CLI.

**Comment by PatMyron** [comment]
was added in botocore 1.16.19:

`pip3 install botocore --upgrade`

https://github.com/boto/botocore/blame/2e08e10d3b5836c4304b30c706a9167cbecda05f/botocore/data/cloudformation/2010-05-15/service-2.json#L3366

https://github.com/boto/botocore/commit/f959dde395917ee770f171002cf85aba7fb29a4c#diff-c9eb8f09352c1c8a08ff7298a8462a03

https://github.com/boto/botocore/releases/tag/1.16.19

---

https://github.com/aws-cloudformation/cloudformation-cli/blob/master/setup.py will need to be pinned more recently

**Comment by bkabrda** [comment]
@wbingli thanks for the response!

It looks like my AWS CLI is a bit outdated, as it doesn't have the `--execution-role-arn` argument for `aws cloudformation register-type`, so that is likely the culprit (I didn't have an override CF CLI model). Anyway, I don't need to invoke AWS APIs in the handler, so I used `--no-role` and that made it work for me. Thanks for the advice!
