### ISSUE TITLE
cfn submit fails to upload to CF Registry: The security token included in the request is invalid

### ISSUE THREAD

**Issue by mtttcgcg** [aws-cloudformation/cloudformation-cli#513]
Hi,
I'm trying to follow the Java tutorial (https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-walkthrough.html) and I got to the part where you try to upload the resource type to the CF Registry.

```
cfn submit -v --region us-east-1
Validating your resource specification...
Creating capitalgroup-okta-app-role-stack
=== Caught downstream error ===
An error occurred (InvalidClientTokenId) when calling the CreateStack operation: The security token included in the request is invalid.
---
If debugging indicates this is a possible error with this program,
please report the issue to the team and include the log file 'rpdk.log'.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues

```
rpdk.log shows:

```
[2020-07-24T02:17:28Z] INFO     - Validating your resource specification...
[2020-07-24T02:17:28Z] DEBUG    - Rewriting refs in '<BASE>' (file:///C:/Work/Zoom/resourceTypePoc/capitalgroup-okta-app.json)
[2020-07-24T02:17:28Z] DEBUG    - overrides.json not found. Not writing to package.
[2020-07-24T02:17:28Z] DEBUG    - inputs not found. Not writing to package.
[2020-07-24T02:17:28Z] DEBUG    - Packaging Java project started
[2020-07-24T02:17:28Z] DEBUG    - Packaging Java project complete
[2020-07-24T02:17:28Z] DEBUG    - Packaging complete, uploading...
[2020-07-24T02:17:28Z] DEBUG    - Uploading to region 'us-east-1'
[2020-07-24T02:17:28Z] DEBUG    - Creating execution role for provider to use
[2020-07-24T02:17:28Z] INFO     - Creating capitalgroup-okta-app-role-stack
[2020-07-24T02:17:29Z] DEBUG    - capitalgroup-okta-app-role-stack stack create resulted in unknown ClientError
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\rpdk\core\upload.py", line 93, in _create_or_update_stack
    Capabilities=["CAPABILITY_IAM"],
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\botocore\client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the CreateStack operation: The security token included in the request is invalid.
[2020-07-24T02:17:29Z] DEBUG    - Caught downstream error
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\rpdk\core\upload.py", line 93, in _create_or_update_stack
    Capabilities=["CAPABILITY_IAM"],
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\botocore\client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the CreateStack operation: The security token included in the request is invalid.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\rpdk\core\cli.py", line 98, in main
    args.command(args)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\rpdk\core\submit.py", line 21, in submit
    args.set_default,
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\rpdk\core\project.py", line 359, in submit
    f, endpoint_url, region_name, role_arn, use_role, set_default
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\rpdk\core\project.py", line 547, in _upload
    self.root / ROLE_TEMPLATE_FILENAME, self.hypenated_name
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\rpdk\core\upload.py", line 151, in create_or_update_role
    template, "{}-role-stack".format(resource_type)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\rpdk\core\upload.py", line 127, in _create_or_update_stack
    raise DownstreamError("Unknown CloudFormation error") from e
rpdk.core.exceptions.DownstreamError: Unknown CloudFormation error
```

If I instead invoke it using a role: cfn submit -v --region us-east-1 --role-arn <my-role-arn>, the log differs slightly:

```

[2020-07-24T21:23:50Z] DEBUG    - Packaging Java project complete
[2020-07-24T21:23:50Z] DEBUG    - Packaging complete, uploading...
[2020-07-24T21:23:50Z] DEBUG    - Uploading to region 'us-east-1'
[2020-07-24T21:23:50Z] INFO     - Creating CloudFormationManagedUploadInfrastructure
[2020-07-24T21:23:51Z] DEBUG    - CloudFormationManagedUploadInfrastructure stack create resulted in unknown ClientError
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\rpdk\core\upload.py", line 93, in _create_or_update_stack
    Capabilities=["CAPABILITY_IAM"],
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\botocore\client.py", line 635, in make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the CreateStack operation: The security token included in the request is invalid.
[2020-07-24T21:23:51Z] DEBUG    - Caught downstream error
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\rpdk\core\upload.py", line 93, in _create_or_update_stack
    Capabilities=["CAPABILITY_IAM"],
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\botocore\client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the CreateStack operation: The security token included in the request is invalid.
> 

```
No resources are uploaded to the private CF Registry. Any ideas?

**Comment by rjlohan** [comment]
This error indicates that you haven't configured your AWS CLI credentials correctly for the CloudFormation CLI to make AWS APIs on your behalf. Follow the instructions [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) to get that setup, and make sure your IAM identity (user/role) has permissions to call the APIs which are used in these operations (e.g; `cloudformation:createStack`)
