### ISSUE TITLE
Contract tests not using role arn if specified for all client calls

### ISSUE THREAD

**Issue by ninavolkmuth** [aws-cloudformation/cloudformation-cli#544]
Contract tests should use temporary credentials from the role arn for all client calls if a role is specified for the contract tests. This should be done when listing the cloudformation exports as well as when getting the account id.

Line references:
https://github.com/aws-cloudformation/cloudformation-cli/blob/033606a83cbd49387272f3ec2c8515459c8724b0/src/rpdk/core/boto_helpers.py#L82
https://github.com/aws-cloudformation/cloudformation-cli/blob/033606a83cbd49387272f3ec2c8515459c8724b0/src/rpdk/core/test.py#L62

**Comment by advaj** [comment]
Im using CLI v0.1.11 and I have just run into this issue again. 

`Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpdk/core/test.py", line 193, in test
    args.role_arn,
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpdk/core/test.py", line 151, in get_inputs
    f.read(), region_name, endpoint_url, role_arn
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpdk/core/test.py", line 79, in render_jinja
    exports = get_cloudformation_exports(region_name, endpoint_url, role_arn)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpdk/core/test.py", line 69, in get_cloudformation_exports
    for page in pages:
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListExports operation: User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/aws-waf-rule-role-stack-ExecutionRole-9JV7FH7SN92V/CloudFormationContractTest-20201005095317 is not authorized to perform: cloudformation:ListExports
`

**Comment by ninavolkmuth** [comment]
@advaj You need to add ListExports to your list of permissions for your role. That is unrelated to this issue

**Comment by ninavolkmuth** [comment]
This issue was released as part of v0.1.8 and was solved in the pull request: https://github.com/aws-cloudformation/cloudformation-cli/pull/548

**Comment by rapphil** [comment]
Shouldn't the role that execute the contract, that is created by the cfn cli, have this permission out of box?
