### ISSUE TITLE
unhandled exception: json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by HanliangJiang** [aws-cloudformation/cloudformation-cli#582]
I added the inputs folder and three json files (inputs_1_create.json, inputs_1_update.json and inputs_1_invalid.json). Then I run the following command.

cfn test --enforce-timeout 120
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
Please include the log file 'rpdk.log'

The rpdk.log is the following.
```
[2020-09-18T22:08:56Z] DEBUG    - Rewriting refs in '<BASE>' (file:///Users/hanlia/CFNBootcamp/aws-cloudformation-resource-providers-mediastore/aws-mediastore-container/aws-mediastore-container.json)
[2020-09-18T22:08:56Z] DEBUG    -   '#/definitions/MetricPolicy' -> '#/definitions/MetricPolicy'
[2020-09-18T22:08:56Z] DEBUG    -   '#/definitions/MetricPolicyRule' -> '#/definitions/MetricPolicyRule'
[2020-09-18T22:08:56Z] DEBUG    -   '#/definitions/CorsRule' -> '#/definitions/CorsRule'
[2020-09-18T22:08:56Z] DEBUG    -   '#/definitions/Tag' -> '#/definitions/Tag'
[2020-09-18T21:21:04Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/Library/Python/3.8/site-packages/rpdk/core/test.py", line 177, in test
    overrides = get_overrides(
  File "/Library/Python/3.8/site-packages/rpdk/core/test.py", line 99, in get_overrides
    overrides_raw = render_jinja(f.read(), region_name, endpoint_url)
  File "/Library/Python/3.8/site-packages/rpdk/core/test.py", line 88, in render_jinja
    to_return = json.loads(overrides_string)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Then I delete the overrides.json. Then the rpdg.log becomes the following.
```
[2020-09-18T21:47:22Z] DEBUG    - Override file '/Users/hanlia/CFNBootcamp/aws-cloudformation-resource-providers-mediastore/aws-mediastore-container/overrides.json' not found. No overrides will be applied
[2020-09-18T21:47:22Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/Library/Python/3.8/site-packages/rpdk/core/test.py", line 183, in test
    inputs = get_inputs(
  File "/Library/Python/3.8/site-packages/rpdk/core/test.py", line 147, in get_inputs
    overrides_raw = render_jinja(f.read(), region_name, endpoint_url)
  File "/Library/Python/3.8/site-packages/rpdk/core/test.py", line 88, in render_jinja
    to_return = json.loads(overrides_string)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by PatMyron** [comment]
Did you rebuild your package in between deleting `overrides.json` and running `cfn test` again?

`mvn clean package`

**Comment by HanliangJiang** [comment]
Yes, I run mvn package but didn't run mvn clean package. Now I remove the inputs folder and only leave the overrides.json. There is no unhandled exception. but I saw the error messages after I start local lambda.
```
2020-09-22 11:58:49 127.0.0.1 - - [22/Sep/2020 11:58:49] "POST /2015-03-31/functions/TypeFunction/invocations HTTP/1.1" 200 -
Invoking software.amazon.mediastore.container.HandlerWrapper::handleRequest (java8)
Decompressing /Users/hanlia/CFNBootcamp/aws-cloudformation-resource-providers-mediastore/aws-mediastore-container/target/aws-mediastore-container-handler-1.0-SNAPSHOT.jar
Failed to download a new amazon/aws-sam-cli-emulation-image-java8:rapid-1.1.0 image. Invoking with the already downloaded image.
Mounting /private/var/folders/hz/n791flpd7f954bwh7qsvy4m03ymx45/T/tmpg9ih8e6r as /var/task:ro,delegated inside runtime container
22 Sep 2020 18:59:09,220 [INFO] (lambdainternal.AWSLambda.startRuntime(AWSLambda.java:287)) JVM runtime reported running (invokeId: dummy)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
Is there a way to solve this problem?

**Comment by cmgorton** [comment]
We are working on answering and cleaning up stale issues. 

@HanliangJiang if this is still an unanswered question for you, please feel free to reopen this issue so we can investigate it further. 

You can also ask questions in our [AWS CloudFormation Discord](https://discord.gg/tmV2gfqh) channel for a more prompt response.
