### ISSUE TITLE
KeyError: 'import_path'

### ISSUE THREAD

**Issue by ThisIsQasim** [aws-cloudformation/cloudformation-cli#606]
Getting the following error when trying to run `cfn generate` in https://github.com/aws-quickstart/quickstart-amazon-eks-cluster-resource-provider. Reverting to cloudformation-cli-go-pluign 2.0.1 seems to fix it.

```
[2020-10-22T11:00:10Z] DEBUG    - Logging set up successfully
[2020-10-22T11:00:10Z] DEBUG    - Running generate: Namespace(command=<function generate at 0x7fd9b52da0d0>, subparser_name='generate', verbose=0, version=False)
[2020-10-22T11:00:10Z] DEBUG    - Root directory: /build
[2020-10-22T11:00:10Z] DEBUG    - Loading project file '/build/.rpdk-config'
[2020-10-22T11:00:10Z] INFO     - Validating your resource schema...
[2020-10-22T11:00:10Z] DEBUG    - Rewriting refs in '<BASE>' (file:///build/awsqs-eks-cluster.json)
[2020-10-22T11:00:10Z] DEBUG    - Writing Resource Role CloudFormation template: /build/resource-role.yaml
[2020-10-22T11:00:10Z] DEBUG    - Overwriting '/build/resource-role.yaml'
[2020-10-22T11:00:10Z] DEBUG    - Generate started
[2020-10-22T11:00:10Z] DEBUG    - Writing Types
[2020-10-22T11:00:10Z] DEBUG    - Overwriting '/build/cmd/resource/model.go'
[2020-10-22T11:00:10Z] DEBUG    - Writing project: /build/cmd/main.go
[2020-10-22T11:00:10Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/usr/lib/python3.8/site-packages/rpdk/core/generate.py", line 15, in generate
    project.generate()
  File "/usr/lib/python3.8/site-packages/rpdk/core/project.py", line 338, in generate
    return self._plugin.generate(self)
  File "/usr/lib/python3.8/site-packages/rpdk/go/codegen.py", line 172, in generate
    importpath = Path(project.settings["import_path"])
KeyError: 'import_path'
```

**Comment by jaymccon** [comment]
looks like this is caused by a change in the go-plugin https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/issues/177
