### ISSUE TITLE
Waiter issue in cloudformation

### ISSUE THREAD

**Issue by sriram9707** [aws-cloudformation/cloudformation-cli#648]
Hello,
I am facing an issue with the waiter for cloudformation.
```
Preparing package...
Submitting...
b"=== Unhandled exception ===\nPlease report this issue to the team.\nIssue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues\nPlease include the log file 'rpdk.log'\n"
Traceback (most recent call last):
File "submit.py", line 28, in
check_call(['cfn', 'submit', '--set-default'], resourcedir.absolute())
File "submit.py", line 18, in check_call
cmd=args)
subprocess.CalledProcessError: Command '['cfn', 'submit', '--set-default']' returned non-zero exit status 127.

boto==2.49.0
boto3==1.14.48
botocore==1.17.48
```
Please post your views to resolve

**Comment by jotompki** [comment]
could you post the rpdk.log ?

**Comment by anshikg** [comment]
@sriram9707 is this still an issue?
