### ISSUE TITLE
VersionConflict after upgrading CFN cli

### ISSUE THREAD

**Issue by shaneyuan18** [aws-cloudformation/cloudformation-cli#653]
Hi, 

I have tried to upgrade the cli with following command. 
`pip3 install cloudformation-cli cloudformation-cli-java-plugin --upgrade
`

This resulted in a version conflict and the cfn cli is completely unfunctional. I have tried uninstall and reinstalling CLI, but similar result.

When I ran `cfn version`
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/cli.py", line 83, in main
    init_setup_subparser(subparsers, parents)
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/init.py", line 168, in setup_subparser
    language_setup_subparser()(language_subparsers, [base_subparser])
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (cloudformation-cli 0.2.1 (/usr/local/lib/python3.9/site-packages), Requirement.parse('cloudformation-cli<0.2,>=0.1.2'))


```

**Comment by shaneyuan18** [comment]
After running upgrade on following packages. The version conflict is resolved

```
cloudformation-cli-python-plugin
cloudformation-cli-go-plugin
```
