### ISSUE TITLE
Invalid date in Module fragment - error is not clear to the user

### ISSUE THREAD

**Issue by priyanka-amzn** [aws-cloudformation/cloudformation-cli#692]
When a yaml template is used with a non-string date, the error message to the user is not clear. 

If the module fragment starts with
```
AWSTemplateFormatVersion: 2010-09-09
```
instead of
```
AWSTemplateFormatVersion: "2010-09-09"
```

The output for `cfn validate` is:
```
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
Please include the log file 'rpdk.log'
```

**Comment by priyanka-amzn** [comment]
fragments/sample.json
```
AWSTemplateFormatVersion: 2010-09-09
Description: A secure S3 Bucket. The features are Versioning and DeletionPolicy.
Parameters:
  BucketName:
    Description: Name for the bucket
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref 'BucketName'
      VersioningConfiguration:
        Status: Enabled
```

rpdk.log
```
[2021-02-26T01:05:36Z] INFO     - Validating your module fragments...
[2021-02-26T01:05:36Z] DEBUG    - Fragment directory: /Users/priyaha/testDate/fragments
[2021-02-26T01:05:36Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/usr/local/lib/python3.7/site-packages/rpdk/core/validate.py", line 14, in validate
    project.load()
  File "/usr/local/lib/python3.7/site-packages/rpdk/core/project.py", line 421, in load
    self._validate_fragments(template_fragment)
  File "/usr/local/lib/python3.7/site-packages/rpdk/core/project.py", line 440, in _validate_fragments
    template_fragment.validate_fragments()
  File "/usr/local/lib/python3.7/site-packages/rpdk/core/fragment/generator.py", line 80, in validate_fragments
    self.__validate_fragment_thru_cfn_lint(raw_fragments)
  File "/usr/local/lib/python3.7/site-packages/rpdk/core/fragment/generator.py", line 83, in __validate_fragment_thru_cfn_lint
    lint_warnings = self.__get_cfn_lint_matches(raw_fragments)
  File "/usr/local/lib/python3.7/site-packages/rpdk/core/fragment/generator.py", line 108, in __get_cfn_lint_matches
    json.dump(raw_fragment, outfile, indent=4)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
```

**Comment by MalikAtalla-AWS** [comment]
Solved by [this commit](https://github.com/aws-cloudformation/cloudformation-cli/commit/bc3cbf5ab83db2b0748a1a2cc24169754077d908) in Version 0.2.4
