### ISSUE TITLE
docker ContextualVersionConflict

### ISSUE THREAD

**Issue by jomakori** [aws-cloudformation/cloudformation-cli#706]
I'm having an issue running 'cfn init' on the console. 
I've been attempting to setup my environment using these instructions: https://github.com/aws-cloudformation/cloudformation-cli

```bash
=== Unhandled exception ===

Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/rpdk/core/cli.py", line 83, in main
    init_setup_subparser(subparsers, parents)
  File "/Library/Python/3.8/site-packages/rpdk/core/init.py", line 195, in setup_subparser
    language_setup_subparser()(language_subparsers, [base_subparser])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docker 4.2.0 (/Library/Python/3.8/site-packages), Requirement.parse('docker>=4.3.1'), {'cloudformation-cli'})
jomakori@3c22fb21c9e8 AWSCloudFormationResourceProvidersEFS % 
```

**Comment by benbridts** [comment]
I assume you're getting that while running pip install. It looks like you might already have another tool installed that installed a different version of the python `docker` library (you have 4.2.0, the cloudformation-cli requires at least 4.3.1).

There are multiple ways to resolve this, depending on how you ended up with the docker 4.3.1.

As an example, I use [pipx](https://github.com/pipxproject/pipx), and using that you can replace the `pip install` command with
```
pipx install cloudformation-cli
pipx inject cloudformation-cli cloudformation-cli-java-plugin cloudformation-cli-go-plugin cloudformation-cli-python-plugin 
```

If you can figure out where that docker 4.2.0 came from and/or upgrade it to a newer version, that might be a solution where you don't have to learn a new tool though.

**Comment by PatMyron** [comment]
likely conflicting with `aws-sam-cli`:
https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/147#issuecomment-759169281
