### ISSUE TITLE
cfn generate gives error while running on windows 10 enterprise, build 18363.1500

### ISSUE THREAD

**Issue by crajeeva** [aws-cloudformation/cloudformation-cli#743]
```
== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include this information:
Traceback (most recent call last):
  File "C:\Users\crajeeva\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\rpdk\core\cli.py", line 83, in main
    init_setup_subparser(subparsers, parents)
  File "C:\Users\crajeeva\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\rpdk\core\init.py", line 166, in setup_subparser
    language_setup_subparser()(language_subparsers, [base_subparser])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\site-packages\pkg_resources\__init__.py", line 2460, in load
    self.require(*args, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\site-packages\pkg_resources\__init__.py", line 2483, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\site-packages\pkg_resources\__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (aws-sam-translator 1.25.0 (c:\users\crajeeva\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages), Requirement.parse('aws-sam-translator>=1.35.0'), {'cfn-lint'})
```

**Comment by PatMyron** [comment]
Upgrading that dependency should help:
`pip3 install aws-sam-translator --upgrade`
