### ISSUE TITLE
Unhandled Exception: ContextualVersionConflict with PyYAML

### ISSUE THREAD

**Issue by mikey-** [aws-cloudformation/cloudformation-cli#745]
I have recently submitted a [PR](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/52) on [aws-cloudformation-resource-providers-rds](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds), which is using codebuild to run CI/CD, which is currently failing. While I don't have access to the build logs, I have been provided with the excerpt below and asked to open an issue here.

```
[2021-04-29T00:37:09Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpdk/core/generate.py", line 14, in generate
    project.load()
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpdk/core/project.py", line 412, in load
    self.load_settings()
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpdk/core/project.py", line 201, in load_settings
    self.validate_and_load_resource_settings(raw_settings)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpdk/core/project.py", line 230, in validate_and_load_resource_settings
    self._plugin = load_plugin(raw_settings["language"])
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpdk/core/plugin_registry.py", line 27, in load_plugin
    return PLUGIN_REGISTRY[language]()()
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyYAML 5.1.2 (/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages), Requirement.parse('pyyaml>=5.4; python_version != "3.4" and python_version != "3.5"'), {'cfn-lint'})
```

Any help you can provide would be greatly appreciated :) Thank you!

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cfn-python-lint/pull/1992
Try upgrading:
`pip3 install pyyaml --upgrade`

**Comment by mikey-** [comment]
Ah, I see! Thank you so much :^) You're a legend!

**Comment by mikey-** [comment]
Worked a treat, thanks again :)

**Comment by mikey-** [comment]
Worked a treat, thanks again :)
