### ISSUE TITLE
cloudformation-cli test failed

### ISSUE THREAD

**Issue by chenrui333** [aws-cloudformation/cloudformation-cli#757]
```
$ cat rpdk.log
[2021-05-12T04:17:02Z] DEBUG    - Logging set up successfully
[2021-05-12T04:17:02Z] DEBUG    - Running None: Namespace(version=False, subparser_name=None, command=<function init at 0x11681cdc0>, verbose=0, force=False, type_name=None, artifact_type=None)
[2021-05-12T04:17:02Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/Cellar/cloudformation-cli/0.2.9/libexec/lib/python3.9/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/usr/local/Cellar/cloudformation-cli/0.2.9/libexec/lib/python3.9/site-packages/rpdk/core/init.py", line 151, in wrapper
    function(args)
  File "/usr/local/Cellar/cloudformation-cli/0.2.9/libexec/lib/python3.9/site-packages/rpdk/core/init.py", line 130, in init
    project = Project(args.force)
  File "/usr/local/Cellar/cloudformation-cli/0.2.9/libexec/lib/python3.9/site-packages/rpdk/core/project.py", line 142, in __init__
    loader=PackageLoader(__name__, "templates/"),
  File "/usr/local/Cellar/cloudformation-cli/0.2.9/libexec/lib/python3.9/site-packages/jinja2/loaders.py", line 309, in __init__
    raise ValueError(
ValueError: The 'rpdk.core.project' package was not installed in a way that PackageLoader understands.
```

---

relates to https://github.com/Homebrew/homebrew-core/pull/77088

**Comment by PatMyron** [comment]
seems to be:
https://github.com/pallets/jinja/issues/1148
https://github.com/pallets/jinja/issues/1168
https://github.com/aws-cloudformation/cloudformation-cli/blob/bc24cc789dee04173018d0625a29c0bc97145c66/setup.py#L42
but not sure if we intend to support homebrew anyway
