### ISSUE TITLE
docker VersionConflict

### ISSUE THREAD

**Issue by hardwaysun** [aws-cloudformation/cloudformation-cli#759]
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include this information:
Traceback (most recent call last):
  File "/home/xsun/.local/lib/python3.8/site-packages/rpdk/core/cli.py", line 83, in main
    init_setup_subparser(subparsers, parents)
  File "/home/xsun/.local/lib/python3.8/site-packages/rpdk/core/init.py", line 168, in setup_subparser
    language_setup_subparser()(language_subparsers, [base_subparser])
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (docker 5.0.0 (/home/xsun/.local/lib/python3.8/site-packages), Requirement.parse('docker<5,>=3.7'))

have python 3.8 and did the install of 
pip3 install cloudformation-cli cloudformation-cli-python-plugin
no issue. Just can't init project.
docker was intalled  Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2

**Comment by PatMyron** [comment]
installing a specific version of `docker` should mitigate this:
`pip install docker==4.3.1 --force-reinstall`
https://github.com/aws-cloudformation/cloudformation-cli/issues/727
https://github.com/aws-cloudformation/cloudformation-cli/issues/706
https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/147

**Comment by hardwaysun** [comment]
Thanks PatMyron, it works with downgrade docker to 4.3.1 and urllib3 to 1.25.11 and jinja to 2.11.1
