### ISSUE TITLE
Please include the log file 'rpdk.log'

### ISSUE THREAD

**Issue by RaviRk0522** [aws-cloudformation/cloudformation-cli#760]
Trying to run below command getting  issue as to include log file  rpdk.log

$ cfn init
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include the log file 'rpdk.log'

**Comment by RaviRk0522** [comment]
cat rpdk.log
[2021-05-16T04:36:53Z] DEBUG    - Logging set up successfully
[2021-05-16T04:36:53Z] DEBUG    - Running None: Namespace(artifact_type=None, command=<function init at 0x7f3934735040>, force=False, subparser_name=None, type_name=None, verbose=0, version=False)
[2021-05-16T04:36:53Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/init.py", line 151, in wrapper
    function(args)
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/init.py", line 130, in init
    project = Project(args.force)
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/project.py", line 142, in __init__
    loader=PackageLoader(__name__, "templates/"),
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/jinja2/loaders.py", line 309, in __init__
    raise ValueError(
ValueError: The 'rpdk.core.project' package was not installed in a way that PackageLoader understands.
[2021-05-16T04:39:40Z] DEBUG    - Logging set up successfully
[2021-05-16T04:39:40Z] DEBUG    - Running None: Namespace(artifact_type=None, command=<function init at 0x7f38f812f040>, force=False, subparser_name=None, type_name=None, verbose=0, version=False)
[2021-05-16T04:39:40Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/init.py", line 151, in wrapper
    function(args)
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/init.py", line 130, in init
    project = Project(args.force)
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/project.py", line 142, in __init__
    loader=PackageLoader(__name__, "templates/"),
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/jinja2/loaders.py", line 309, in __init__
    raise ValueError(
ValueError: The 'rpdk.core.project' package was not installed in a way that PackageLoader understands.
[2021-05-16T04:59:55Z] DEBUG    - Logging set up successfully
[2021-05-16T04:59:55Z] DEBUG    - Running None: Namespace(artifact_type=None, command=<function init at 0x7fcb84526040>, force=False, subparser_name=None, type_name=None, verbose=0, version=False)
[2021-05-16T04:59:55Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/init.py", line 151, in wrapper
    function(args)
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/init.py", line 130, in init
    project = Project(args.force)
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/rpdk/core/project.py", line 142, in __init__
    loader=PackageLoader(__name__, "templates/"),
  File "/home/ec2-user/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/jinja2/loaders.py", line 309, in __init__
    raise ValueError(
ValueError: The 'rpdk.core.project' package was not installed in a way that PackageLoader understands.

**Comment by benbridts** [comment]
similar to #758 and #757 

can you try downgrading the installed jinja with `pip install Jinja2==2.11.3`?
