### ISSUE TITLE
Unable to submit a module from YAML fragment

### ISSUE THREAD

**Issue by antoineVIVIES** [aws-cloudformation/cloudformation-cli#807]
Hello,
I ran into this problem while using this command:
```bash
~ cfn submit --region ap-southeast-1
Module fragment is valid.
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include the log file 'rpdk.log'
```
Here is an extract of the rpdk.log:
```bash
[2021-08-10T07:41:12Z] WARNING  - Module fragment is valid.
[2021-08-10T07:41:12Z] DEBUG    - Overwriting '/Users/antoinevivies/Documents/UnaBiz/unaconnect-backend/config/schema.json'
[2021-08-10T07:41:12Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/submit.py", line 15, in submit
    project.submit(
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/project.py", line 502, in submit
    zip_file.write(self.schema_path, SCHEMA_UPLOAD_FILENAME)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1727, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 501, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/antoinevivies/Documents/UnaBiz/unaconnect-backend/config/unabiz-sqssns-newregion-module.json'
```
It looks like that there is a file that is supposed to be created it doesn't.
I'm on MacOS BigSur version 11.4 with intel processor.
The template looks valid because cfn-lint is clean.
Let me know if you need more informations

Thanks,
Antoine

**Comment by MalikAtalla-AWS** [comment]
Hi Antoine. Thanks for raising this. We are aware of the issue and working on a fix. The temporary workaround is reverting to an older version of the CLI. Have a look at [this issue](https://github.com/aws-cloudformation/cloudformation-cli/issues/793).

**Comment by MalikAtalla-AWS** [comment]
Hey @antoineVIVIES. This issue is resolved in the latest version of the cloudformation-cli:
https://github.com/aws-cloudformation/cloudformation-cli/releases/tag/v0.2.16

**Comment by antoineVIVIES** [comment]
Working Thanks ! 🎉
