### ISSUE TITLE
cfn cli fails to install following the provided instructions

### ISSUE THREAD

**Issue by mailuminatti** [aws-cloudformation/cloudformation-cli#864]
While following the installation instructions detailed in the guide, cfn cli fails to install. 
Command used for installation: 
```python3 -m venv env
source env/bin/activate
pip3 install cloudformation-cli cloudformation-cli-python-plugin
pip3 install --upgrade cloudformation-cli cloudformation-cli-python-plugin
```
Result when running `cfn init`

```
Traceback (most recent call last):
  File "/home/ec2-user/environment/CloudFormationCLI/env/bin/cfn", line 5, in <module>
    from rpdk.core.cli import main
  File "/home/ec2-user/environment/CloudFormationCLI/env/lib64/python3.7/site-packages/rpdk/core/cli.py", line 12, in <module>
    from .build_image import setup_subparser as build_image_setup_subparser
  File "/home/ec2-user/environment/CloudFormationCLI/env/lib64/python3.7/site-packages/rpdk/core/build_image.py", line 11, in <module>
    from .project import Project
  File "/home/ec2-user/environment/CloudFormationCLI/env/lib64/python3.7/site-packages/rpdk/core/project.py", line 12, in <module>
    from jinja2 import Environment, PackageLoader, select_autoescape
  File "/home/ec2-user/environment/CloudFormationCLI/env/lib64/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/ec2-user/environment/CloudFormationCLI/env/lib64/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/ec2-user/environment/CloudFormationCLI/env/lib64/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/ec2-user/environment/CloudFormationCLI/env/lib64/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/ec2-user/environment/CloudFormationCLI/env/lib64/python3.7/site-packages/markupsafe/__init__.py)
```

To clarify, markupsafe is already installed:

```pip install markupsafe
Requirement already satisfied: markupsafe in /home/ec2-user/environment/CloudFormationCLI/env/lib/python3.7/site-packages (2.1.0)``

**Comment by osdrv** [comment]
In our case the failure happens upon a `cfn generate` invocation.

The issue seems to be very similar to https://github.com/aws/aws-sam-cli/issues/3661.

**Comment by beck3905** [comment]
I am experiencing this error too when I used `cfn submit`.  Is anyone working on a fix yet?

**Comment by osdrv** [comment]
@ammokhov 's patch fixed my problem. Many thanks!
