### ISSUE TITLE
cfn submit fails for the below reason

### ISSUE THREAD

**Issue by kartikmathpal** [aws-cloudformation/cloudformation-cli#873]
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include this information:
Traceback (most recent call last):
  File "/home/mathpalk/.local/lib/python3.7/site-packages/rpdk/core/cli.py", line 83, in main
    init_setup_subparser(subparsers, parents)
  File "/home/mathpalk/.local/lib/python3.7/site-packages/rpdk/core/init.py", line 171, in setup_subparser
    language_setup_subparser()(language_subparsers, [base_subparser])
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2460, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2483, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docker 4.2.2 (/local/home/mathpalk/.local/lib/python3.7/site-packages), Requirement.parse('docker>=4.3.1'), {'cloudformation-cli'})

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cloudformation-cli/issues/706#issuecomment-802401675
https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/147#issuecomment-759169281
`pip install docker==4.3.1 --force-reinstall`

**Comment by mmaeng** [comment]
PatMyron's pip command should sort you out but please hit us up on [AWS CloudFormation Discord](https://discord.gg/tmV2gfqh) if you are still running into issues!

Closing this for now.
