### ISSUE TITLE
Caught Downstream Error with `cfn submit`

### ISSUE THREAD

**Issue by tjbrockmeyer** [aws-cloudformation/cloudformation-cli#877]
OS: Windows 10 Pro 64-bit

I am trying to `cfn submit` to register a resource type that I've developed, but I am receiving some errors.

This is the output of running `cfn submit`:
```
Resource schema is valid.
Starting build.
=== Caught downstream error ===
[WinError 2] The system cannot find the file specified
---
If debugging indicates this is a possible error with this program,
please report the issue to the team and include the log file 'rpdk.log'.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
```

Inspecting the logs, it appears that the issue is resulting from the command it uses to start the build:
`npm install --optional && sam build --debug --build-dir C:\Coding\code\web\infra\aws\custom-resources\tjb-ssm-securestring/build --use-container TypeFunction`

But if I run that command in isolation, it builds the function in the `./build` directory with no issues.

Here is the full log output:
```
[2022-04-11T02:58:30Z] DEBUG    - Logging set up successfully
[2022-04-11T02:58:30Z] DEBUG    - Running submit: Namespace(version=False, subparser_name='submit', command=<function submit at 0x000001FAA5EE7940>, verbose=0, dry_run=False, endpoint_url=None, region=None, set_default=False, role_arn=None, use_role=True)
[2022-04-11T02:58:30Z] DEBUG    - Root directory: C:\Coding\code\web\infra\aws\custom-resources\tjb-ssm-securestring
[2022-04-11T02:58:30Z] DEBUG    - Loading project file 'C:\Coding\code\web\infra\aws\custom-resources\tjb-ssm-securestring\.rpdk-config'
[2022-04-11T02:58:30Z] INFO     - Validating your resource specification...
[2022-04-11T02:58:30Z] DEBUG    - Rewriting refs in '<BASE>' (file:///C:/Coding/code/web/infra/aws/custom-resources/tjb-ssm-securestring/tjb-ssm-securestring.json)
[2022-04-11T02:58:30Z] WARNING  - Resource schema is valid.
[2022-04-11T02:58:30Z] INFO     - Validating your resource schema...
[2022-04-11T02:58:30Z] DEBUG    - inputs not found. Not writing to package.
[2022-04-11T02:58:30Z] DEBUG    - Package started
[2022-04-11T02:58:30Z] DEBUG    - 'C:\Coding\code\web\infra\aws\custom-resources\tjb-ssm-securestring\build' not found, skipping removal
Traceback (most recent call last):
  File "c:\coding\frameworks\python\python3.9.1\lib\site-packages\rpdk\typescript\codegen.py", line 215, in _remove_build_artifacts
    shutil.rmtree(deps_path)
  File "c:\coding\frameworks\python\python3.9.1\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\coding\frameworks\python\python3.9.1\lib\shutil.py", line 599, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "c:\coding\frameworks\python\python3.9.1\lib\shutil.py", line 596, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Coding\\code\\web\\infra\\aws\\custom-resources\\tjb-ssm-securestring\\build'
[2022-04-11T02:58:30Z] DEBUG    - Dependencies build started from 'C:\Coding\code\web\infra\aws\custom-resources\tjb-ssm-securestring'
[2022-04-11T02:58:30Z] DEBUG    - command is 'npm install --optional && sam build --debug --build-dir C:\Coding\code\web\infra\aws\custom-resources\tjb-ssm-securestring/build --use-container TypeFunction'
[2022-04-11T02:58:30Z] WARNING  - Starting build.
[2022-04-11T02:58:30Z] DEBUG    - Caught downstream error
Traceback (most recent call last):
  File "c:\coding\frameworks\python\python3.9.1\lib\site-packages\rpdk\typescript\codegen.py", line 243, in _build
    completed_proc = subprocess_run(  # nosec
  File "c:\coding\frameworks\python\python3.9.1\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\coding\frameworks\python\python3.9.1\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\coding\frameworks\python\python3.9.1\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\coding\frameworks\python\python3.9.1\lib\site-packages\rpdk\core\cli.py", line 100, in main
    args.command(args)
  File "c:\coding\frameworks\python\python3.9.1\lib\site-packages\rpdk\core\submit.py", line 15, in submit
    project.submit(
  File "c:\coding\frameworks\python\python3.9.1\lib\site-packages\rpdk\core\project.py", line 650, in submit
    self._add_resources_content_to_zip(zip_file)
  File "c:\coding\frameworks\python\python3.9.1\lib\site-packages\rpdk\core\project.py", line 678, in _add_resources_content_to_zip
    self._plugin.package(self, zip_file)
  File "c:\coding\frameworks\python\python3.9.1\lib\site-packages\rpdk\typescript\codegen.py", line 204, in package
    self._build(project.root)
  File "c:\coding\frameworks\python\python3.9.1\lib\site-packages\rpdk\typescript\codegen.py", line 251, in _build
    raise DownstreamError("local build failed") from e
rpdk.core.exceptions.DownstreamError: local build failed
```

**Comment by mmaeng** [comment]
This looks to be an issue in cloudformation-cli-typescript-plugin module.  I've created Issue #[cloudformation-cli-typescript-plugin issue 75](https://github.com/aws-cloudformation/cloudformation-cli-typescript-plugin/issues/75) so we can track this.

**Comment by mmaeng** [comment]
Hi,  The fix is live in the master branch of the typescript plugin.  Until it gets packaged up and released you will have to install the fix manually

1. clone the repo to your local machine https://github.com/aws-cloudformation/cloudformation-cli-typescript-plugin
2. Then it would be activate your virtual environment (if you are using one, we would recommend this as per python best practices)
3. run `pip install -e .` from the downloaded repo directory to install the newest patches.

Hope that helps!

**Comment by sahil9677** [comment]
I tried this, get the following error,

[2022-11-07T22:49:57Z] DEBUG    - Logging set up successfully
[2022-11-07T22:49:57Z] DEBUG    - Running submit: Namespace(version=False, subparser_name='submit', command=<function submit at 0x000001E6BD12B490>, verbose=0, dry_run=False, endpoint_url=None, region=None, set_default=True, role_arn=None, use_role=True)
[2022-11-07T22:49:57Z] DEBUG    - Root directory: C:\Users\sahil\shield-advance-cfn
[2022-11-07T22:49:57Z] DEBUG    - Loading project file 'C:\Users\sahil\shield-advance-cfn\.rpdk-config'
[2022-11-07T22:49:57Z] INFO     - Validating your resource specification...
[2022-11-07T22:49:57Z] WARNING  - Explicitly specify value for tagging
[2022-11-07T22:49:57Z] DEBUG    - Rewriting refs in '<BASE>' (file:///C:/Users/sahil/shield-advance-cfn/gs-dmz-shieldadvance.json)
[2022-11-07T22:49:57Z] WARNING  - Resource schema is valid.
[2022-11-07T22:49:57Z] INFO     - Validating your resource schema...
[2022-11-07T22:49:57Z] DEBUG    - inputs not found. Not writing to package.
[2022-11-07T22:49:57Z] DEBUG    - Package started
[2022-11-07T22:49:57Z] DEBUG    - Dependencies build started from 'C:\Users\sahil\shield-advance-cfn'
[2022-11-07T22:49:57Z] DEBUG    - command is 'npm install --optional && sam build --debug --build-dir C:\Users\sahil\shield-advance-cfn\build --use-container TypeFunction'
[2022-11-07T22:49:57Z] WARNING  - Starting build.
[2022-11-07T22:50:04Z] DEBUG    - Caught downstream error
Traceback (most recent call last):
  File "C:\Users\sahil\venv\lib\site-packages\rpdk\typescript\codegen.py", line 265, in _build
    completed_proc = subprocess_run(  # nosec
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\WINDOWS\\system32\\cmd.exe', '/C', 'npm install --optional && sam build --debug --build-dir C:\\Users\\sahil\\shield-advance-cfn\\build --use-container TypeFunction']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sahil\venv\lib\site-packages\rpdk\core\cli.py", line 100, in main
    args.command(args)
  File "C:\Users\sahil\venv\lib\site-packages\rpdk\core\submit.py", line 15, in submit
    project.submit(
  File "C:\Users\sahil\venv\lib\site-packages\rpdk\core\project.py", line 650, in submit
    self._add_resources_content_to_zip(zip_file)
  File "C:\Users\sahil\venv\lib\site-packages\rpdk\core\project.py", line 678, in _add_resources_content_to_zip
    self._plugin.package(self, zip_file)
  File "C:\Users\sahil\venv\lib\site-packages\rpdk\typescript\codegen.py", line 220, in package
    self._build(project.root)
  File "C:\Users\sahil\venv\lib\site-packages\rpdk\typescript\codegen.py", line 284, in _build
    raise DownstreamError("local build failed") from e
rpdk.core.exceptions.DownstreamError: local build failed

**Comment by mmaeng** [comment]
@sahil9677 Please try with the new cloudformation-cli 0.2.26 was just released with quite a few Windows fixes.  The plugin and the base cloudformation-cli have quite a few interconnections.

**Comment by sahil9677** [comment]
I tried that still get the same error as above.

**Comment by mmaeng** [comment]
@sahil9677

Hmmm are you able to run

`docker ps`
`sam --version`
`npm --version`

Those would be what the cfn CLI tools have to run to generate the artifacts.
