### ISSUE TITLE
Private Python registry for Hooks

### ISSUE THREAD

**Issue by maslick** [aws-cloudformation/cloudformation-cli#890]
Is it possible to run ``cfn generate`` (e.g. when deploying a CloudFormation Hook to AWS) using a private PyPI registry?
I have a custom logic inside my Hook, that requires a library within a private PyPI registry (residing in a private CodeArtifact Python repo).

Steps to reproduce:
```bash
aws configure
export AWS_REGION="eu-west-1"

cfn init
cfn generate
cfn submit --set-default --region $AWS_REGION -v
```

**.rpdk-config**
```
{
    "artifact_type": "HOOK",
    "typeName": "Cfn::Tags::Hook",
    "language": "python37",
    "runtime": "python3.7",
    "entrypoint": "cfn_tags_hook.handlers.hook",
    "testEntrypoint": "cfn_tags_hook.handlers.test_entrypoint",
    "settings": {
        "version": false,
        "subparser_name": null,
        "verbose": 0,
        "force": false,
        "type_name": null,
        "artifact_type": null,
        "endpoint_url": null,
        "region": null,
        "target_schemas": [],
        "use_docker": true,
        "protocolVersion": "2.0.0"
    }
}

```

**rpdk.log**
```
[2022-06-16T10:10:37Z] DEBUG    - Logging set up successfully
[2022-06-16T10:10:37Z] DEBUG    - Running submit: Namespace(version=False, subparser_name='submit', command=<function submit at 0x11b3becb0>, verbose=1, dry_run=True, endpoint_url=None, region='eu-west-1', set_default=False, role_arn=None, use_role=True)
[2022-06-16T10:10:37Z] DEBUG    - Root directory: /Users/a1337/cfn-tags-hook
[2022-06-16T10:10:37Z] DEBUG    - Loading project file '/Users/a1337/cfn-tags-hook/.rpdk-config'
[2022-06-16T10:10:37Z] INFO     - Validating your hook specification...
[2022-06-16T10:10:37Z] DEBUG    - Rewriting refs in '<BASE>' (file:///Users/a1337/cfn-tags-hook/tags-hook.json)
[2022-06-16T10:10:37Z] DEBUG    - inputs not found. Not writing to package.
[2022-06-16T10:10:38Z] DEBUG    - aws-s3-bucket.json found. Writing to package.
[2022-06-16T10:10:38Z] DEBUG    - Package started
[2022-06-16T10:10:39Z] DEBUG    - Dependencies build started from '/Users/a1337/cfn-tags-hook'
[2022-06-16T10:10:39Z] DEBUG    - command is 'pip install --no-cache-dir --no-color --disable-pip-version-check --upgrade --requirement /project/requirements.txt --target /project/build'
[2022-06-16T10:10:39Z] WARNING  - Starting Docker build. This may take several minutes if the image 'lambci/lambda:build-python3.7' needs to be pulled first.
[2022-06-16T10:10:39Z] DEBUG    - Trying paths: ['/Users/a1337/.docker/config.json', '/Users/a1337/.dockercfg']
[2022-06-16T10:10:39Z] DEBUG    - Found file at path: /Users/a1337/.docker/config.json
[2022-06-16T10:10:39Z] DEBUG    - Found 'auths' section
[2022-06-16T10:10:39Z] DEBUG    - Auth data for 355xxxxxxxxxx.dkr.ecr.eu-central-1.amazonaws.com is absent. Client might be using a credentials store instead.
[2022-06-16T10:10:39Z] DEBUG    - Auth data for 566yyyyyyyyyy.dkr.ecr.eu-west-1.amazonaws.com is absent. Client might be using a credentials store instead.
[2022-06-16T10:10:39Z] DEBUG    - Found 'credsStore' section
[2022-06-16T10:10:40Z] DEBUG    - Caught downstream error
Traceback (most recent call last):
  File "/usr/local/Cellar/cloudformation-cli/0.2.25/libexec/lib/python3.10/site-packages/rpdk/python/codegen.py", line 285, in _docker_build
    logs = docker_client.containers.run(
  File "/usr/local/Cellar/cloudformation-cli/0.2.25/libexec/lib/python3.10/site-packages/docker/models/containers.py", line 848, in run
    raise ContainerError(
docker.errors.ContainerError: Command 'pip install --no-cache-dir --no-color --disable-pip-version-check --upgrade --requirement /project/requirements.txt --target /project/build' in image 'lambci/lambda:build-python3.7' returned non-zero exit status 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/cloudformation-cli/0.2.25/libexec/lib/python3.10/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/usr/local/Cellar/cloudformation-cli/0.2.25/libexec/lib/python3.10/site-packages/rpdk/core/submit.py", line 15, in submit
    project.submit(
  File "/usr/local/Cellar/cloudformation-cli/0.2.25/libexec/lib/python3.10/site-packages/rpdk/core/project.py", line 648, in submit
    self._add_hooks_content_to_zip(zip_file, endpoint_url, region_name)
  File "/usr/local/Cellar/cloudformation-cli/0.2.25/libexec/lib/python3.10/site-packages/rpdk/core/project.py", line 713, in _add_hooks_content_to_zip
    self._plugin.package(self, zip_file)
  File "/usr/local/Cellar/cloudformation-cli/0.2.25/libexec/lib/python3.10/site-packages/rpdk/python/codegen.py", line 227, in package
    self._build(project.root)
  File "/usr/local/Cellar/cloudformation-cli/0.2.25/libexec/lib/python3.10/site-packages/rpdk/python/codegen.py", line 246, in _build
    self._docker_build(base_path)
  File "/usr/local/Cellar/cloudformation-cli/0.2.25/libexec/lib/python3.10/site-packages/rpdk/python/codegen.py", line 303, in _docker_build
    raise DownstreamError("Error running docker build") from e
rpdk.core.exceptions.DownstreamError: Error running docker build

```

**requirements.txt**
```
cloudformation-cli-python-lib>=2.1.9
my-private-lib==0.0.1
```

So it seems, when using ``"use_docker": true`` it can't fetch private dependencies from a public Python registry, and there's no way to tell cfn to use private docker registry credentials...

**Comment by maslick** [comment]
I've been able to resolve this issue by setting ``"use_docker": false`` and using ``lambci/lambda:build-python3.7`` Docker image (which is internally used by ``cfn`` if ``use_docker`` is set to ``true`` and which mimics Lambda environment) on the CI and executing the following steps:
- create and activate a new Python venv
- authenticate against your private Python registry (e.g. CodeArtifact)
- install cfn cli (``pip install cloudformation-cli cloudformation-cli-python-plugin``)
- install dependencies (``pip install -r requirements.txt``)
- deploy hook (``cfn submit --set-default --region $REGION -v``)
