### ISSUE TITLE
Expired AWS credentials throws unhandled exception

### ISSUE THREAD

**Issue by mmaeng** [aws-cloudformation/cloudformation-cli#925]
commands like `cfn test` throws unhandled exception error if your AWS credentials have expired or are not present.

A more useful error would be helpful instead of diving into logs to identify the issue.

**Comment by mmaeng** [comment]
Command output
```
cfn test
Explicitly specify value for insertionOrder for array: Authors
Explicitly specify value for tagging
Resource schema is valid.
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include the log file 'rpdk.log'
```
Excerpt from logs
```
[2022-10-20T16:48:24Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/Users/mmaeng/Documents/source/mmaeng/cloudformation-cli/src/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/Users/mmaeng/Documents/source/mmaeng/cloudformation-cli/src/rpdk/core/test.py", line 397, in test
    invoke_test(args, project, overrides, None)
  File "/Users/mmaeng/Documents/source/mmaeng/cloudformation-cli/src/rpdk/core/test.py", line 401, in invoke_test
    plugin_clients = get_contract_plugin_client(args, project, overrides, inputs)
  File "/Users/mmaeng/Documents/source/mmaeng/cloudformation-cli/src/rpdk/core/test.py", line 345, in get_contract_plugin_client
    plugin_clients["resource_client"] = ResourceClient(
  File "/Users/mmaeng/Documents/source/mmaeng/cloudformation-cli/src/rpdk/core/contract/resource_client.py", line 179, in __init__
    self.account = get_account(
  File "/Users/mmaeng/Documents/source/mmaeng/cloudformation-cli/src/rpdk/core/boto_helpers.py", line 95, in get_account
    response = sts_client.get_caller_identity()
  File "/Users/mmaeng/Documents/source/mmaeng/cloudformation-cli/.venv/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mmaeng/Documents/source/mmaeng/cloudformation-cli/.venv/lib/python3.10/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the GetCallerIdentity operation: The security token included in the request is expired
```

**Comment by PatMyron** [comment]
Catching and handling every specific exception is a never-ending treadmill for no reason

https://github.com/aws-cloudformation/cloudformation-cli/pull/121 causes more confusion swallowing exceptions into `.log` files and telling everyone their unhandled exception should be reported:

https://github.com/aws-cloudformation/cloudformation-cli/blob/df37e649de9a49f290c680ea81e5656334889a51/src/rpdk/core/cli.py#L132-L138

instead of just showing these straightforward exceptions (rest of stacktrace doesn't need to be shown):

`An error occurred (ExpiredToken) when calling the GetCallerIdentity operation: The security token included in the request is expired`
