### ISSUE TITLE
Unhandled exception when was trying to run cfn at first time

### ISSUE THREAD

**Issue by YuchengMaUTK** [aws-cloudformation/cloudformation-cli#938]
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include this information:
Traceback (most recent call last):
  File "/home/yuchma/.local/lib/python3.7/site-packages/rpdk/core/cli.py", line 83, in main
    init_setup_subparser(subparsers, parents)
  File "/home/yuchma/.local/lib/python3.7/site-packages/rpdk/core/init.py", line 171, in setup_subparser
    language_setup_subparser()(language_subparsers, [base_subparser])
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2460, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2483, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (MarkupSafe 2.0.1 (/local/home/yuchma/.local/lib/python3.7/site-packages), Requirement.parse('MarkupSafe>=2.1.1'), {'Werkzeug', 'werkzeug'})

got this message after pip install cfn, not familiar before. Can you team guide me how to fix this?

**Comment by mmaeng** [comment]
Hi @YuchengMaUTK 

We are working on resolving this python requirements conflict.

For the moment if you update your pip
`pip install --upgrade pip`
then install again that should resolve the conflicts.
`pip install cloudformation-cli`

Please let us know if that helps!  We are also available on [AWS CloudFormation Discord](https://discord.gg/tmV2gfqh)!

**Comment by mmaeng** [comment]
Adding link to more detailed issue #940 that is causing this error
